- Makefile
- config/install/field.storage.node.field_landing_page_show_contact.yml
- config/install/field.storage.node.field_news_intro_text.yml
- config/install/field.storage.node.field_node_primary_site.yml
- config/install/field.storage.node.field_node_site.yml
- config/install/media.type.image.yml
- config/install/taxonomy.vocabulary.audience.yml
- config/install/taxonomy.vocabulary.sites.yml
- taxonomy.vocabulary.sites.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-904
1.
> [SDPA-904] Add event content type

- config/install/field.storage.block_content.field_tags.yml
- config/install/field.storage.block_content.field_topic.yml
- tide_core.info.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-94
> [SDPA-94] Added Topic and Tags field storage for custom blocks.

- config/install/field.storage.node.field_landing_page_contact.yml
- tide_core.info.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1028
1.  Move field.storage.node.field_landing_page_contact from tide_landing_page
> [SDPA-1028] Add Contact Us paragraph & reorganise the layout

- config/install/field.storage.node.field_show_topic_term_and_tags.yml
- tide_core.info.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-446
Related PR: #22 
**Changes**
1. Added the new config to "config_devel".
> [SDPA-446] Moved show_topic_term_and_tags field storage to tide_core.

- composer.json
Jira Story: https://digital-engagement.atlassian.net/browse/SDPA-1073
**Changes**
1. Remove better expose filters patch
**Screenshots**
> [SDPA-1073] Remove better expose filters patch

- composer.json
- config/install/core.entity_form_display.paragraph.timeline.default.yml
- config/install/core.entity_form_display.paragraph.timelines.default.yml
- config/install/core.entity_view_display.paragraph.timeline.default.yml
- config/install/core.entity_view_display.paragraph.timelines.default.yml
- config/install/entity_browser.browser.tide_image_browser.yml
- config/install/field.field.paragraph.timeline.field_paragraph_body.yml
- config/install/field.field.paragraph.timeline.field_paragraph_cta_text.yml
- config/install/field.field.paragraph.timeline.field_paragraph_date_range.yml
- config/install/field.field.paragraph.timeline.field_paragraph_link.yml
- config/install/field.field.paragraph.timeline.field_paragraph_media.yml
- config/install/field.field.paragraph.timeline.field_paragraph_title.yml
- config/install/field.field.paragraph.timelines.field_paragraph_title.yml
- config/install/field.field.paragraph.timelines.field_timeline.yml
- config/install/field.storage.media.field_media_department.yml
- config/install/field.storage.media.field_media_license.yml
- config/install/field.storage.paragraph.field_paragraph_body.yml
- config/install/field.storage.paragraph.field_paragraph_cta_text.yml
- config/install/field.storage.paragraph.field_paragraph_title.yml
- config/install/field.storage.paragraph.field_timeline.yml
- config/install/media.type.document.yml
- config/install/media.type.image.yml
- config/install/paragraphs.paragraphs_type.timeline.yml
- config/install/paragraphs.paragraphs_type.timelines.yml
- config/install/views.view.tide_media_browser.yml
- tests/behat/features/timelines.feature
- tide_core.info.yml
Story: https://digital-engagement.atlassian.net/browse/SDPA-741
Changes:
- Added Timeline and Timelines paragraph bundles since they are being re-used across multiple content types.
> [SDPA-741]: Added Timeline and Timelines paragraph bundles.

- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--timeline.yml
Story: https://digital-engagement.atlassian.net/browse/SDPA-1359
- Swapped "created" field enhancer to user timestamp instead of string.
> [SDPA-1359]: Timeline fixed date formatter.

- config/install/core.entity_form_display.paragraph.timeline.default.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1370
Content PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/
1.  Replace Body by Summary in Timeline paragraph
> [SDPA-1370] Replace Body by Summary in Timeline paragraph

- composer.json
- config/install/field.field.paragraph.timelines.field_timeline.yml
- config/install/field.storage.paragraph.field_timeline.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1368
Content PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/368
1.  Update paragraphs version
> [SDPA-1368] Update paragraphs version

- config/install/views.view.tide_media_browser.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1470
Content PR: 
Tide Landing Page  PR: 
Tide Media  PR: https://github.com/dpc-sdp/tide_media/pull/15
1.  Update tide browser view to add display to list media embedded content
> [SDPA-1470] Update tide browser view to add display to list media embedded content

- config/install/filter.format.rich_text.yml
- config/optional/editor.editor.rich_text.yml
- tests/behat/features/wysiwyg.toolbar.feature
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1807
1.  Enable IFrame on Rich Editor
> [SDPA-1807] Enable IFrame on Rich Editor

- tide_core.drush.inc
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2026
Content PR: 
1.  Add Drush 8 command to run scheduled updates cron
> [SDPA-2026] Add Drush 8 command to run scheduled updates cron

- composer.json
- dev-tools.sh
- includes/helpers.inc
> Reworked config import utility.

- composer.json
- config/optional/pathauto.settings.yml
- includes/helpers.inc
> Updated optional Pathauto settings.

- composer.json
- dev-tools.sh
1. Removed [entity_embed patch](https://www.drupal.org/project/entity_embed/issues/2832504) that no longer applied.
> Removed unrequired patch.

- tide_core.install
- tide_core.module
adds `field_purge_batch()` before uninstalling scheduled_updates
> [SDPA-2742] adds field_purge_batch before uninstalling scheduled_updates

- config/optional/metatag.metatag_defaults.node.yml
- tide_core.install
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-3087
> Added featured mage to og:image metatag of nodes.

- tide_core.install
- tide_core.module
https://digital-engagement.atlassian.net/browse/SDPA-3157
relates to https://github.com/dpc-sdp/content-vic-gov-au/pull/679
more details see https://github.com/dpc-sdp/content-vic-gov-au/pull/679
> [SDPA-3157] Imported default permissions to approver and site_admin.

- config/install/user.role.previewer.yml
- tide_core.install
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-3189
> Fixed permissions for Previewers.

- composer.json
Fixed unrecognised entity operation passed to Menu Link Content throws exceptions
https://www.drupal.org/project/drupal/issues/3016038
test Steps
1. Login to back end
2. Go to Menu> pick a main menu then select edit option for any link eg https://www.develop.content.vic.gov.au/admin/structure/menu/item/906/edit?destination=/admin/structure/menu
Result
correct page returns
> [SDPA-3190] Fixed unrecognised entity operation

- config/optional/clamav.settings.yml
- tide_core.install
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-1082
1. Updated clamav.settings in optional
2. Added update hook to change clamav config to use central service.
> [SDPSUP-1082] Added clamav config to use central service.

- composer.json
Locking linkit module to 5.0-beta9.
> locked linkit to beta9.

- composer.json
1. Locked version of field_group
> Locked version of field_group.

- composer.json
- tests/behat/features/clamav.feature
https://www.drupal.org/project/viewsreference/issues/3096956#comment-13370643
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
The service "viewsreference.normalizer.views_reference_item.hal" has a dependency on a non-existent service "hal.link_manager". 
```
> Fixing a dependency issue

- composer.json
Removes smart_trim patch merged into the latest release https://www.drupal.org/project/smart_trim/issues/2941492
> Removed smart_trim patch merged into latest release.

- composer.json
- modules/tide_workflow_notification/config/install/queue_mail.settings.yml
- modules/tide_workflow_notification/tide_workflow_notification.info.yml
- modules/tide_workflow_notification/tide_workflow_notification.install
https://digital-engagement.atlassian.net/browse/SDPA-3557
1. Adding queue_mail module as tide_workflow_notification's dependency
2. Adding a hook_update and configs yaml file.
relates to https://github.com/dpc-sdp/content-vic-gov-au/pull/758
> SDPA-3557 added queue_mail

- config/install/user.role.approver.yml
- config/install/user.role.editor.yml
- config/install/user.role.site_admin.yml
- tide_core.install
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3453
1.  Added permission to access embedded video browser editor, approver & site-admin.
> [SDPA-3453] Added permission to access embedded video browser for editor, approver & siteadmin.

- modules/tide_workflow_notification/config/install/tide_workflow_notification.settings.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-1309
1.  Updated token and static links to remove the bracket, so that it doesn't get added with the link.
> [SDPSUP-1309] Updated tide_workflow_notification settings to fix links.

- composer.json
https://digital-engagement.atlassian.net/browse/SDPA-3778
1. https://www.drupal.org/project/drupal/issues/2693485#comment-11004325
- the ticket in drupal.org has been marking as `Needs work`. but patch `#3` works.
https://github.com/dpc-sdp/content-vic-gov-au/pull/794
> SDPA-3778 alphabetical order

- tide_core.module
https://digital-engagement.atlassian.net/browse/SDPA-3779
1. the form_alter only happens when the element of['revision_log'] exists.
> [SDPA-3779] fixes unexpected element

- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPSUP-1680
1. Added a check in Update hook 8019 to see if the tide_workflow_notification module exists before applying the settings update for tide_workflow_notification module.
> [SDPSUP-1680] Added tide_workflow_notification module existence check before applying settings update.

- composer.json
https://digital-engagement.atlassian.net/browse/SDPA-4315
the query takes about 2 minutes to render, or sometimes it returns 502.
- https://www.drupal.org/project/drupal/issues/3097303
- it should be fixed by core since `drupal 9.1`
https://github.com/dpc-sdp/content-vic-gov-au/pull/880
> [SDPA-4315] Poor performance when using moderation

- composer.json
https://digital-engagement.atlassian.net/browse/SDPSUP-1711
1. Added patches for the password policy module.
> [SDPSUP-1711] Added password_policy patches.

- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-3946
1. Updating the accordion content name and body field mandatory.
Related content-vic PR with the exported setting - https://github.com/dpc-sdp/content-vic-gov-au/pull/891
> [SDPA-3946] Added hook to update accordion fields to be mandatory.

- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4351
1. disabling cloudflare module if it is enabled.
> [SDPA-4351] enabling Cloudflare module

- composer.json
https://digital-engagement.atlassian.net/browse/SDPA-4332
https://www.drupal.org/project/inline_entity_form/issues/3160683
> [SDPA-4332] WYSIWYG media picker creating duplicate entries

- composer.json
https://digital-engagement.atlassian.net/browse/SW-320
```
Invalid display settings encountered. Could not process following      [warning]
settings for entity type "media" with the uuid
"d22a4da8-1022-4903-9dad-d5d28648bca9":
```
Added patch for entity_embed module. Patch - https://www.drupal.org/project/entity_embed/issues/3077225
> [SW-320] Added patch for entity embed module.

- config/install/filter.format.admin_text.yml
- config/install/filter.format.rich_text.yml
- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4091
>Update install config for admin_text and rich_text  filter formats
change `<td>` to `<td colspan rowspan align>`
change `<th>`to `<th colspan rowspan align>`
Add an update hook to set new values for the html filter.
> [SDPA-4091] changes allowed HTML list

- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-2970
1. apply `d/m/Y - H:i` to the view.
> [SDPA-2970] change display of dates in CMS to Australian style DD/MM/YYYY

- config/install/field.storage.node.field_landing_page_contact.yml
- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-2959
https://digital-engagement.atlassian.net/browse/SDPA-4461
1. change `cardinality` to 2 to `field.storage.node.field_landing_page_contact.yml`
https://github.com/dpc-sdp/content-vic-gov-au/pull/933
> [SDPA-4661] enable addtional contact block

- config/install/core.entity_form_display.paragraph.accordion.default.yml
- config/install/field.field.paragraph.accordion.field_paragraph_accordion_style.yml
- config/install/field.field.paragraph.accordion.field_paragraph_title.yml
- config/install/field.field.paragraph.accordion_content.field_paragraph_accordion_body.yml
- config/install/field.field.paragraph.accordion_content.field_paragraph_accordion_name.yml
- config/install/field.storage.paragraph.field_paragraph_accordion_style.yml
- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4329
1. change labels and styles by an update hook
> [SDPA-4329] cms improvements accordin

- config/optional/editor.editor.summary_text.yml
- config/optional/filter.format.summary_text.yml
- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4572
add two new filter and format editor entity.
> [SDPA-4572] imports new format and editor entity

- composer.json
https://digital-engagement.atlassian.net/browse/SDPA-4613
1. upgrades drupal core to 8.8.10
> [SDPA-4613] upgrade to drupal 8.8.10

- config/install/user.role.approver.yml
- config/install/user.role.editor.yml
- config/install/user.role.site_admin.yml
- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4610
Non administrators are not able to edit new summary_text fields
1. update yml configs.
2. add an update hook to updating permissions.
> [SDPA-4610] update permissions

- composer.json
- dev-tools.sh
- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4334
1. Added CKeditor liststyle module and the dependency package.
2. Repository for the dependency package added in the dev-tools.
3. Release task created in ansible to add the dependency package repository in the root composer.
Dev-tools - https://github.com/dpc-sdp/dev-tools/pull/40
Ansible release task - https://github.com/dpc-sdp/sdp-ansible-upgrade/pull/26
https://github.com/dpc-sdp/content-vic-gov-au/pull/976
> [SDPA-4334] Added CKeditor liststyle module.

- config/install/user.role.editor.yml
- tests/behat/features/access.feature
- tide_core.install
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3733
1.  Removed permissions for the editor's role to access redirects.
> [SDPA-3733] Removed permissions for editor to access redirects.

- composer.json
https://digital-engagement.atlassian.net/browse/SDPA-4830
1. upgrade core to 8.8.x
> [SDPA-4830] upgrade core to 8.8.x

- composer.json
- dev-tools.sh
https://digital-engagement.atlassian.net/browse/SDPA-4790
> [SDPA-4790] upgrade drupalcore to 8.9.x

- composer.json
- tide_core.info.yml
- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4755
> add quick_node_clone module

- composer.json
New release of token fixes the patch - https://www.drupal.org/project/token/releases/8.x-1.8
> [remove-token-module-patch] Rremoved patch for token module.

- config/optional/editor.editor.admin_text.yml
- config/optional/editor.editor.rich_text.yml
- config/optional/editor.editor.summary_text.yml
- tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4811
Enable Maximize button in wysiwyg toolbar
http://nginx-php-content-vic-pr-1024.lagoon.vicsdp.amazee.io/
> [SDPA-4811] Enable Maximize button in wysiwyg toolbar

- composer.json
> Replaced core Xss patch for 8.9.14.

- tide_core.install
> Only enabled tide_edit_protection if its role dependency is met.

- config/optional/user.role.anonymous.yml
- modules/tide_edit_protection/config/install/views.view.tide_locked_content.yml
1. clean up default_config_hash from `user.role.anonymous.yml `
2. clean up `event_author` and `grant_author` role from `tide_locked_content` view.
> Fixes dependency issues

- tide_core.install
> Fixes lint issue

- composer.json
- tide_core.drush.inc
Revert the changes that are made for drush update.
> [revert-drush-updates] Removed changes required for drush update.

- tide_core.info.yml
- tide_core.install
**JIRA issue:** https://digital-engagement.atlassian.net/browse/DDS-808
1.  Add missing dependencies for install
2. Add checking on CKEditor config update so that config doesn't get corrupted.
> Implement scaffold and fix reference build

- modules/tide_edit_protection/config/optional/views.view.tide_locked_content.yml
- modules/tide_edit_protection/tide_edit_protection.info.yml
- modules/tide_edit_protection/tide_edit_protection.install
- modules/tide_edit_protection/tide_edit_protection.module
- modules/tide_edit_protection/tide_edit_protection.permissions.yml
https://digital-engagement.atlassian.net/browse/SDPA-5210
1. adds new permission
2. refactor `tide_lock_content`
> [SDPA-5210] Refactors tide_lock_content view

- src/TideEntityUpdateHelper.php
- tide_core.services.yml
https://digital-engagement.atlassian.net/browse/SDPA-5275
1. We have been seeing lots of entity update issues, some of them is hard to debug and fix.
2. This helper class could be used for 
- get entity schema data.
- get field entity schema data.
- reinstall missed table.
> [SDPA-5275] a helper class for dealing with entity update issues.

- modules/tide_edit_protection/config/optional/views.view.tide_locked_content.yml
- modules/tide_edit_protection/tide_edit_protection.install
https://digital-engagement.atlassian.net/browse/SDPA-5548
1. update `uid_current` filter's label to `Is the user logged in right now?`
> Updates uid_current form label

- config/install/field.storage.node.field_location.yml
- tide_core.install
https://digital-engagement.atlassian.net/browse/SRM-228
1. change the yaml file.
2. add an update hook.
also added it to release branch, so this PR doesn't need to be merging and releasing urgently 
https://github.com/dpc-sdp/sdp-ansible-upgrade/blob/239fa28639153db0336f358cf74b5504ae4b1dbb/tasks/release/1.37.0/tasks.yml#L137-L147
> [SRM-228] Changes field_location's cardinality

- composer.json
https://digital-engagement.atlassian.net/browse/SDPA-5935
1. https://github.com/dpc-sdp/tide_core/blob/develop/composer.json#L224 is outdated.
1. re-roll to capture updates to the base branch (tag: 1.7) , works with Drupal9.2.10
2. https://www.drupal.org/project/metatag/issues/2945817#comment-14345350
> [SDPA-5935] Updates metatag's patch

- modules/tide_dashboard/tide_dashboard.module
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5931
1. Checked and set URL redirect destination when available.
Example url part to use: **/?destination=/admin/config/content/embed**
**BEFORE**
**AFTER**
> [SDPA-5931] Fixed "Log in now" link for CMS redirection

- composer.json
- tide_core.module
https://digital-engagement.atlassian.net/browse/SDPA-5923
remove permissions_by_term out of from tide_core.
> [SDPA-5923] Remove permissions_by_term module

- modules/tide_jira/tide_jira.module
Ticket: https://digital-engagement.atlassian.net/browse/SDPSUP-3951
Changed:
1) Resolve crash when saving a new node as "Needs Review" status.
> [SDPSUP-3951] Fix hook implementations

- composer.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5663
1. Added patch fix for ASC sort for multipage list.
> [SDPA-5663] Patched CMS menus page in alphabetical order

- composer.json
Issue
The patch is already merged in the new release of jira rest. Unlock module to allow future versions.
Changes
Patch is removed.
Patch link
https://www.drupal.org/project/jira_rest/issues/3252182
Release note of webform
https://www.drupal.org/project/jira_rest/releases/8.x-4.0-beta3
> Removed patch that is removed in recent jira rest release.

- config/install/field.storage.paragraph.field_statistic_block.yml
- config/install/field.storage.paragraph.field_statistic_body.yml
- config/install/field.storage.paragraph.field_statistic_heading.yml
- config/install/field.storage.paragraph.field_statistics_grid_theme.yml
- tide_core.info.yml
- tide_core.install
** Jira ** - https://digital-engagement.atlassian.net/browse/SDPA-5869
* Done due to https://digital-engagement.atlassian.net/browse/SDPA-6075
Changes
1) Add storage definations for the following
* field.storage.paragraph.field_statistic_block
* field.storage.paragraph.field_statistic_body
* field.storage.paragraph.field_statistic_heading
* field.storage.paragraph.field_statistics_grid_theme
> [SDPA-5867] Storage definations for statistic grid

- tide_core.install
https://digital-engagement.atlassian.net/browse/SRM-326
remove `tide_core_update_8048` hook so that it wouldn't be installed during the installation of `tide_core`.
> Remove `login_redirect_per_role` module from the install hook

- tide_core.install
** Jira ** - https://digital-engagement.atlassian.net/browse/SDPA-5452
Changes:
Change the Diff modules revision_pager_limit to 16 in settings
> [SDPA-5452] CMS review page pagination

- composer.json
- modules/tide_jira/README.md
- modules/tide_jira/config/install/jira_rest.jira_endpoint.jira_rest_default.yml
- modules/tide_jira/config/install/tide_jira.settings.yml
- modules/tide_jira/src/Form/TideJiraConfigForm.php
- modules/tide_jira/src/Plugin/QueueWorker/TideJiraProcessorBase.php
- modules/tide_jira/src/TideJiraAPI.php
- modules/tide_jira/src/TideJiraConnector.php
- modules/tide_jira/src/TideJiraTicketModel.php
- modules/tide_jira/tide_jira.services.yml
https://digital-engagement.atlassian.net/browse/SDPSUP-4386
1) Update install config to point to the new Jira instance
2) Implement new Jira field mappings for site, sub-site, departments and content types
3) Misc formatting improvements
> [SDP2-77] tide_jira updates

- config/install/field.storage.node.field_node_display_headings.yml
- tide_core.install
**JIRA** - https://digital-engagement.atlassian.net/browse/SDPA-6233
Parent Ticket - https://digital-engagement.atlassian.net/browse/SDPA-6190
Changed
* Updated text values
* 'showH2' -> 'Show Heading 2s only.'
* 'showH2AndH3' -> 'Show Heading 2s and heading 3s.'
* Added options
* 'showH2AndAccordionTitle' -> 'Show Heading 2s and accordion titles.'
* 'showH2AndH3AndAccordionTitle' -> 'Show Heading 2s, accordion titles and Heading 3s.'
> [SDPA-6233] Add new Display Options for Display Headings

- src/EntityAutocompleteMatcher.php
Suggested change to PR dpc-sdp/tide_core#325
> SDPA-6303: Fix broken handler plugin id

- src/EntityAutocompleteMatcher.php
https://digital-engagement.atlassian.net/browse/SDPA-6303
see the ticket.
> [SDPA-6303] Fixes an issue that causes link field broken

- config/install/editor.editor.admin_text.yml
- config/install/editor.editor.rich_text.yml
- config/install/editor.editor.summary_text.yml
- config/install/filter.format.admin_text.yml
- config/install/filter.format.rich_text.yml
- config/install/filter.format.summary_text.yml
- tide_core.install
**JIRA**
https://digital-vic.atlassian.net/browse/SDPAP-6026
**Test Environment**
https://nginx-php.pr-89.content-reference-sdp-vic-gov-au.sdp2.sdp.vic.gov.au/
**Changes**
1. Adds editor.editor.admin_text.yml file to config/install
2. Adds editor.editor.rich_text.yml file to config/install
3. Adds editor.editor.summary_text.yml file to config/install
4. Update script in tide_core.install file to update linkit profile and filter weights to avoid editor errors
**Screenshots**
Below are screenshots of the configuration of all 3 editor settings using ckeditor toolbar located at admin/config/content/formats showing profile selected and filter order.
> [SDPA-6026] Unable to easily search and find internal links

- composer.json
- dev-tools.sh
- modules/tide_paragraphs_enhanced_modal/tide_paragraphs_enhanced_modal.module
- src/Plugin/CKEditorPlugin/TideCallout.php
- src/Plugin/CKEditorPlugin/TideEmbeddedGoogleMapsButton.php
- tide_core.install
- tide_core.module
**Jira** : 
1. https://digital-vic.atlassian.net/browse/SRM-512
2. https://digital-vic.atlassian.net/browse/SRM-519
Changes
1. Add `drupal/core": "9.4.x` 
3. Remove the patch drupal/inline_entity_form
4. Reroll metatag patch https://www.drupal.org/project/metatag/issues/2945817#comment-14716597
> Feature/srm 512 update drupal to 9.4

- tide_core.module
Ticket: https://digital-vic.atlassian.net/browse/SDPAP-5301
- Create a hook_form_FORM_ID_alter to add headers to unlabelled radio buttons in Revisions Table.
> [SDPAP-5301] Adding headers to unlabelled radio buttons

- tide_core.links.menu.yml
Ticket: https://digital-vic.atlassian.net/browse/SDPAP-5665
- Create a .links.menu.yml file to add a new submenu named Moderated content on Content menu.
[SDPAP-5665.webm](https://user-images.githubusercontent.com/23239224/196368033-46dff1ca-b751-4317-8a1a-e5c61978e66f.webm)
> [SDPAP-5665] Add moderated content submenu to Content Menu

- composer.json
- modules/tide_user_expire/config/install/tide_user_expire.settings.yml
- modules/tide_user_expire/config/schema/tide_user_expire.schema.yml
- modules/tide_user_expire/tide_user_expire.info.yml
- modules/tide_user_expire/tide_user_expire.install
- modules/tide_user_expire/tide_user_expire.module
- tests/behat/features/tide_user_expire.feature
- tide_core.info.yml
- tide_core.install
Jira - https://digital-vic.atlassian.net/browse/SDPAP-5915
**Changes**
- Enable user expiration date
- Create a user notification email template
- Send notification email
> SDPAP-5915: Remove block user account.

- composer.json
https://www.drupal.org/project/admin_audit_trail/issues/3316835
> admin_audit_trail - Latest Release Breaks Pagination

- composer.json
- tide_core.install
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6292
1.  Added patch for horizontal tab validation.
Before:
https://user-images.githubusercontent.com/67810118/204404403-d5443e99-d696-47c0-8610-ec2571c82669.mov
After:
https://user-images.githubusercontent.com/67810118/204404193-940dd19e-9235-4e54-b807-30603fc5a6e8.mov
> [SDPAP-6292] Field not in focus not validating.

- config/install/user.role.approver.yml
- modules/tide_block_inactive_users/src/Plugin/QueueWorker/InactiveRecordsQueue.php
- modules/tide_block_inactive_users/tide_block_inactive_users.module
- modules/tide_jira/tide_jira.module
- tide_core.info.yml
- tide_core.install
https://digital-vic.atlassian.net/browse/SDPAP-7116
approvers don't have permission to break locked content.
adding `break content lock` permission to `approvers`
> [SDPAP-7116] Fixes an issue with approvers role

- composer.json
No Jira ticket
This module got a new release this morning and it breaks the patch that was added for this module.
The Patch has been rerolled https://www.drupal.org/project/site_alert/issues/3156557#comment-14924665
> Updated site_alert patch.

- composer.json
Drupal issue - https://www.drupal.org/project/site_alert/issues/3156557#comment-14930684
The patch that got merged was missing some files. - https://github.com/dpc-sdp/tide_core/pull/372
I have rerolled the patch and test against our reference site and also made a comment in the durpal issue about the testing.
> Added new patch link.

- composer.json
- js/editor_autolink.js
- src/Plugin/Linkit/Matcher/PhoneMatcher.php
> [SRM-666] linkit update

- composer.json
- modules/tide_ckeditor/README.md
- modules/tide_ckeditor/src/Plugin/EmbeddedContent/TideIframe.php
- modules/tide_ckeditor/templates/embedded-content/tide-iframe.html.twig
- modules/tide_ckeditor/tide_ckeditor.module
> [SRM-672] Adds iframe function to ck5

- composer.json
> [SRM-668] Update entity_embed

- composer.json
https://digital-vic.atlassian.net/browse/SRM-688
`typeError: Cannot access offset of type string on string in Drupal\password_policy\Plugin\Validation\Constraint\PasswordPolicyConstraintValidator->validate() (line 63 of /app/docroot/modules/contrib/password_policy/src/Plugin/Validation/Constraint/PasswordPolicyConstraintValidator.php)`
Updated the patch - https://www.drupal.org/project/password_policy/issues/2941526#comment-14938934
> Updated patch.

- composer.json
> Patch Claro missing drap drop paragrahp through table header changes.

- composer.json
- modules/tide_site_alert/config/optional/block.block.tide_site_alert_header.yml
> Ck5 ref tide site alert update

- js/node_revision_log.js
https://digital-vic.atlassian.net/browse/SDPAP-8008
Claro's new theme caused issues.
applying the correct CSS selector fixes the issue.
> [SDPAP-8008] Fixes ‘Change request detail’ issue

- composer.json
- dev-tools.sh
https://digital-vic.atlassian.net/browse/SDPAP-8014
The tool tip wasn't working for the webform module elements.
Updated library versions to match with the new changes made in the drupal webform composer library json. This resolves the conflict and 404 notices and tool tip starts working.
[tide_webform](https://github.com/dpc-sdp/tide_webform/pull/93)
[dev-tools](https://github.com/dpc-sdp/dev-tools/pull/102)
[Ansible hotfix task](https://github.com/dpc-sdp/sdp-ansible-upgrade/pull/147)
Testing PR - https://nginx-php.pr-1558.content-vic.sdp4.sdp.vic.gov.au/user/11438
> [SDPA-8014] webform tooltip fix

- modules/tide_ckeditor/tide_ckeditor.install
- modules/tide_ui_restriction/tide_ui_restriction.module
https://digital-vic.atlassian.net/browse/SDPAP-8007
1. Exclude `/admin/config/content/ckeditor-templates/template-selector/{editor}` from _admin_config_access_check.
2. Assign `use text format advanced` permission to `editor`, `approver` and `site_admin` roles
> [SDPAP-8007] Fixes access issues for ckeditor5

- modules/tide_site_alert/config/optional/block.block.tide_site_alert_header.yml
https://digital-vic.atlassian.net/browse/DDS-1591
> Increased tide_site_alert block refresh frequency to 10 minutes.

- composer.json
https://digital-vic.atlassian.net/browse/SDPAP-7876
As a CMS site admin or admin, I would like to be able to filter the menus page so that I can quickly find the item I need.
Created a patch to add filter by input field to Menu UI
https://nginx-php.pr-310.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
> [SDPAP7876]adding menu ui patch

- modules/tide_oauth/tide_oauth.install
- modules/tide_ui_restriction/tide_ui_restriction.install
- modules/tide_workflow_notification/tide_workflow_notification.module
It is causing issues envs going down whenever it tries to use this. It was caught during a test in the reference site BE.
> Updated deprectaed functions.

- composer.json
https://www.drupal.org/project/entity_embed/issues/3272732
Removed patch that has been release
> Removed patch that is fixed.

- src/TideEntityUpdateHelper.php
- tide_core.post_update.php
https://digital-vic.atlassian.net/browse/SRM-1110
1. add a helper function to get original storage definitions.
2. fixes the problem of content_entity_revision_id field.
> [SRM-1110] Updates helper tools and fixes issue.

- composer.json
- tide_core.info.yml
This module should be added as a require dev in the projects root composer.
Removed it from the core requirement
> Removed devel_entity_updates module.

- modules/tide_cms_support/src/Plugin/Block/HelpBlock.php
Fixes an issue when logging into CMS about the Request class attribute being added dynamically
> Fix issue presenting on login screen with class attributes

- tide_core.install
Content-reference build was failing because hook update wrong configs files
Update hook update
> fixed hook

- modules/tide_ckeditor/src/Plugin/EmbeddedContent/TideIframe.php
[SDPAP-8359] Embed tool - increase character limit for URL field
increase `#maxlength` to `512`, which should be enough.
[SDPAP-8359]: https://digital-vic.atlassian.net/browse/SDPAP-8359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDPAP-8359] increase character limit for url field

- composer.json
The patch was outdated after the new version release of entity embed.
Added the new re-rolled patch against 1.6 version of entity embed.
> Updated the patch to a new re-rolled version agaisnt the new release of entity embed.

- composer.json
https://digital-vic.atlassian.net/browse/R20-1982
https://www.drupal.org/project/drupal/issues/3445910
> [R20-1982] `&nsbp;` appearing in places

- composer.json
https://www.drupal.org/project/content_lock/issues/3343964
A new release was added to fix this issue and we don't need this patch anymore.
> remove patch content lock

- dev-tools.sh
- modules/tide_cms_support/tide_cms_support.links.menu.yml
https://digital-vic.atlassian.net/browse/SDPAP-9269
BE link: https://nginx-php.pr-412.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
We needed to update the new help top menu link.
> [SDPAP-9269]updated help link

- composer.json
https://digital-vic.atlassian.net/browse/SD-134
Patch doesn't apply in the last version of token as the code has been refactored. Therefore, downgrading to version 12 and update to latest available version of the patch.
https://www.drupal.org/project/token/issues/2924873#comment-15705267
> Update token version

- composer.json
1. Field_group module launched a new release and  patches can't being applied.
2. Create site_admin user got 500 page.
1. Rerolled  patches against latest version.
https://www.drupal.org/project/field_group/issues/3098550#comment-15712652
https://www.drupal.org/project/field_group/issues/2894351#comment-15712685
https://www.drupal.org/project/password_policy/issues/3465364#comment-15713319
> added patch for password policy history

- composer.json
[SUPPORT - Content Ref - BE - Iframes not loaded](https://digital-vic.atlassian.net/browse/SD-141)
[&nsbp appearing in places it never used to on reference](https://digital-vic.atlassian.net/browse/SD-143)
- Fixes a HTML `serialize` issue in Drupalcore
- For more details, please refer to the link below
https://www.drupal.org/project/drupal/issues/3445910
> [SD-141] Fixes the iframe not loaded issue.

- composer.json
https://digital-vic.atlassian.net/browse/SD-183
https://www.drupal.org/project/entity_embed/issues/3466609
> [SD-183] Fixes an entity embed caused issue.

- composer.json
The patch is fixed and released in the new version.
Removed the patch.
> Removed patch that has been merged and release for password policy module

- modules/tide_landing_page/src/Helper/TideLandingPageHelper.php
https://digital-vic.atlassian.net/browse/SCFA-884
change `Y-m-d H:i:s` to `\DateTime::ATOM`
https://www.php.net/manual/en/class.datetimeinterface.php#datetimeinterface.constants.atom
> [SCFA-884] Fix localDateAndTimeFormatter to ensure consistency with API response for news content types

- tide_core.module
https://digital-vic.atlassian.net/browse/SD-359
Testing link: https://nginx-php.pr-1717.content-vic.sdp4.sdp.vic.gov.au/ 
Link for language code is not working.
Update url.
> [SD-359] Fix broken link for language codes in Locale field

- modules/tide_site_restriction/src/Plugin/views/field/TideNodeBulkForm.php
https://digital-vic.atlassian.net/browse/SD-418
Error message when search for a content in content-vic.
Adding a validation to current user. 
https://github.com/dpc-sdp/tide_core/pull/517
> [SD-418] add validation delete bulk approver

- modules/tide_webform/tide_webform.module
https://digital-vic.atlassian.net/browse/SD-115
only apply the default `maxlength` to `textfield` type
> [SD-115] Fixes conflicting field validations in textarea and textfield types

- modules/tide_webform/tide_webform.install
- modules/tide_webform/tide_webform.module
https://digital-vic.atlassian.net/browse/SD-482
Rename the machine name from `tide_webform_captcha` to `tide_webform`
> [SD-482] Bug in Tide captcha blocking drush cim

- modules/tide_site/tide_site.install
https://digital-vic.atlassian.net/browse/SD-494
Enabled linkset endpoint for all projects.
> [SD-494] Enable linkset endpoint.

- tide_core.install
https://digital-vic.atlassian.net/browse/SD-563
Added update hook to roll out tide_data_driven_component for all cms
> [SD-563] Added hook to roll out tide_data_driven_component for all cms.

- .github/workflows/build.yml
- .github/workflows/merge_to_reference.yml
> Workflow fixes in git actions

- composer.json
Issue for entity embed https://www.drupal.org/project/entity_embed/issues/3410132#comment-15546646 has been rebased in the version 1.7.
Bump up drupal entity embed to version 1.7
removed patchs entity embed.
> removed entity embed patchs

- modules/tide_landing_page/config/install/core.entity_form_display.paragraph.key_journeys.default.yml
- modules/tide_landing_page/config/install/core.entity_view_display.paragraph.key_journeys.default.yml
- modules/tide_landing_page/tide_landing_page.install
https://digital-vic.atlassian.net/browse/SD-603
Add a tel: 000 formatted link in the header link. Currently Drupal prevents a Editor/Approver to add this in the URL field as it doesn’t match the url validation rule
Replace the Link widget with the Linkit widget for the relevant field.
Testing link: https://nginx-php.pr-1765.content-vic.sdp4.sdp.vic.gov.au/
> [SD-603] tel link header links

- modules/tide_tfa/src/Plugin/TfaSetup/TideTfaEmailOtpSetup.php
https://digital-vic.atlassian.net/browse/SD-643
Fix typo in TFA CMS.
> [SD-643]fixed typo

- modules/tide_api/src/Plugin/jsonapi/FieldEnhancer/YamlEnhancer.php
https://digital-vic.atlassian.net/browse/SD-601
Causing issues at the front end as there was a mistake in the conditional logic.
Fixed conditional logic.
> [SD-601]fixed conditional

- modules/tide_media/tide_media.install
- tide_core.module
https://digital-vic.atlassian.net/browse/SD-722
Adds path and status fields to media document form display.
> [SD-722] Adds path and status fields to media document form display.

- modules/tide_landing_page/tide_landing_page.module
- modules/tide_publication/tide_publication.module
The field can't be saved correctly, because if `#disabled = TRUE` whatever value is in the field will be ignored.
Use form validate instead.
> fix: unable to save Page title display style field

- modules/tide_site/tide_site.module
https://digital-vic.atlassian.net/browse/SD-687
Refactor the code to adapt to the CMDB change.
- https://github.com/dpc-sdp/sdp-cmdb/pull/1584
> [SD-687] set maximum depth of site taxonomy

- modules/tide_landing_page/tide_landing_page.module
- tide_core.module
https://digital-vic.atlassian.net/browse/SD-783
Testing link: https://nginx-php.pr-1824.content-vic.sdp4.sdp.vic.gov.au/
A new change in the header links paragraph has been implemented and an extra information in the help text needs to be done.
Updated help text to header link paragraph.
> [SD-783]added help text to header links

- modules/tide_landing_page/tide_landing_page.module
- modules/tide_webform/src/Plugin/WebformElement/WebformReviewComponent.php
- tide_core.module
https://github.com/dpc-sdp/tide_core/pull/592
https://github.com/dpc-sdp/tide_core/pull/605
https://github.com/dpc-sdp/tide_core/pull/603
> preparation for tide 5.0.8

- modules/tide_publication/tide_publication.install
https://digital-vic.atlassian.net/browse/SD-854
The field storage definition should be removed.
> [SD-854] Restore the content category fields for all content types.

- modules/tide_webform/src/Commands/TideWebformSubmissionsCleanUp.php
1. Remove error_log
2. Only delete submissions marked as processed = 1
> Only delete submissions marked as processed = 1

- modules/tide_jira/config/install/field.storage.taxonomy_term.field_jira_project.yml
- modules/tide_jira/config/install/tide_jira.settings.yml
- modules/tide_jira/src/Form/TideJiraConfigForm.php
- modules/tide_jira/src/TideJiraAPI.php
- modules/tide_jira/tide_jira.install
https://digital-vic.atlassian.net/browse/SD-830
Add a fallback in case the user or node doesn't have a department field attached.
> [SD-830] Update tide_jira module to have a fallback dept

- composer.json
- modules/tide_jira/src/TideJiraAPI.php
1. Rerolled the key patch https://www.drupal.org/project/key/issues/3356052#comment-16093356
2. Fixes a tide_jira issue.
> Rerolled the key patch and fixed tide_jira issue

- composer.json
- modules/tide_jira/src/Plugin/monitoring/SensorPlugin/TideJiraSensorPlugin.php
- modules/tide_jira/src/TideJiraConnector.php
Removed unnecessary patch and refactored the codebase.
> Remove php-jira-rest-client patch

- tide_core.install
https://digital-vic.atlassian.net/browse/SD-447
> Update email templates

- composer.json
- modules/tide_event/tide_event.install
https://digital-vic.atlassian.net/browse/SD-216
https://www.drupal.org/project/webform/issues/3524877
> [SD-216] Fix incompatibility with devel ^5.2

- modules/tide_api/src/Plugin/jsonapi/FieldEnhancer/YamlEnhancer.php
https://digital-vic.atlassian.net/browse/SD-964
The token `[current-date:html_date]` should populate the date field with the current date when the webform is loaded.
Inlcude the token service
> [SD-964] YAML enhancer supports tokens

- modules/tide_site_alert/tests/behat/features/access.feature
- modules/tide_site_alert/tide_site_alert.install
https://digital-vic.atlassian.net/browse/SD-904
1. Added permissions to allow site_admin role to manage site alerts.
2. Behat test added.
> [SD-904] Added permission for site-admin to allow managing site alerts.

- modules/tide_site/tide_site.module
- modules/tide_site_restriction/tide_site_restriction.module
https://digital-vic.atlassian.net/browse/SD-1032
tide_site doesn't have a dependency on the tide_site_restriction module...
> [SD-1032]fixes Media Library not loading issue

- composer.dev.json
- composer.json
The patch is outdated with the new release.
Re-rolled the patch with the new webform release.
> Re-rolled webform patch with the new webform release.

- modules/tide_webform/config/optional/jsonapi_extras.jsonapi_resource_config.webform--webform.yml
- modules/tide_webform/src/Plugin/jsonapi/FieldEnhancer/WebformElementsEnhancer.php
- modules/tide_webform/tests/behat/features/jsonapi.content_rating.feature
- modules/tide_webform/tide_webform.install
https://digital-vic.atlassian.net/browse/SD-1194
The Advanced HTML/Text needs to be processed for the FE to render images.
Added a element enhancer just like basic text enhancer. The structure for webform element data is different as it returns all the elements. This is why the enhancer needs to be added to the elements unlike where the basic text enhancer gets added to a field. For this reason it is better to create a separate enhancer and manipulate the elements. If we need any other manipulation, we can just add function to customise the same enhancer for different elements.
> [SD-1194] Added webform elements enhancer.
