dpc-sdp/tide_core

config/install/field.storage.node.field_show_topic_term_and_tags.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-446
**Changes**
1. Moved show_topic_term_and_tags field storage to tide_core because it is now being used in page and landing page content types.
=> [SDPA-446] Moved show_topic_term_and_tags field storage to tide_core

composer.json, src/Form/EntityArchiveForm.php, tests/behat/features/workflow.feature, tide_core.drush.inc, tide_core.module, tide_core.routing.yml
Story: https://digital-engagement.atlassian.net/browse/SDPA-1207
- Pinned Metatag module version to stop the patch breaking the build (known issue, see #57 )
- Added new custom confirmation Form for entity Archive operation.
- Added custom route that points to the confirmation form mentioned above.
- Added hook_entity_operation that adds the dropdown option "Archive"
- I was unsuccessful with adding Behat tests due to permissions that Workflow generates dynamically. The module checks for "use editorial transition archived" which does not seem to exist during Behat testing.
=> [SDPA-1207] Added content archive operation.

composer.json
Added a patch to Drupal Core to fix an issue with missing custom blocks after `block_content_8600` has run.
=> Added a patch for missing block content.

composer.json, config/optional/workflows.workflow.editorial.yml, src/EventSubscriber/TideCoreRouteAlter.php, tide_core.install, tide_core.links.task.yml, tide_core.module, tide_core.services.yml
https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-3100
Change 'Scheduled transitions' to 'Scheduled updates publishing' on the following: 
Scheduled transitions page ( https://nginx-php-content-vic-pr-616.lagoon.vicsdp.amazee.io/admin/content/scheduled-transitions)
Within the content menu
Content summary page when selecting operations dropdown next to each content summary
In the 'Execute transitions' dropdown hide all options except for 'Publish' and Archive'.
'Scheduled updates ' tab should also be available to the content tab.
=> [SDPA-3100]Altered the scheduled transition’s UI

composer.json, tide_core.install
adds `link_field_autocomplete_filter` module so that link field type can have a UI for exporting configuration.
https://digital-engagement.atlassian.net/browse/SDPA-3015
1. `link_field_autocomplete_filter` looks nice and it should be added into tide_core module so that all link type have config UI if needed.
2. in this PR we don't have any yml configs, because there are no default configs for enabling `link_field_autocomplete_filter` module. users should set the config under an actual site.
=> [SDPA-3015] adds link_field_autocomplete_filter

tide_core.info.yml
https://digital-engagement.atlassian.net/browse/SDPA-3231
removed 
- paragraphs.paragraphs_type.timeline	
- paragraphs.paragraphs_type.timelines
related PRs:
https://github.com/dpc-sdp/content-vic-gov-au/pull/708
https://github.com/dpc-sdp/tide_landing_page/pull/86
=> [SDPA-3231] moved timelines config to tide_core

composer.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-990
1.  Removed patch for maxlength.
The patch link that has been removed - https://www.drupal.org/project/maxlength/issues/2798903
The new release - https://www.drupal.org/project/maxlength/releases/8.x-1.0-beta4
The issue it was having -
=> [SDPSUP-990] Updated removed patch for maxlength.

composer.json, dev-tools.sh
https://digital-engagement.atlassian.net/browse/SDPA-3451
1. Updated dpc-sdp/tide_core to constrain versions of entity_reference_revisions < 1.6.x
dpc-sdp/content-vic-gov-au#740
=> Added version constraint for entity_reference_revisions.

config/optional/clamav.settings.yml
https://digital-engagement.atlassian.net/browse/SDPA-3505
- change `scan_mode` in clamav.settings.yml to 1
I think there is no way to split the configs from module level. the module only has `install` and `option` folder. 
Changing `scan_mode` based on `environment` should happen in global config folder like `config/ci`, `config/dev` `config/local` ?
does CI get ClamAV installed under /usr/bin/...?
=> SDPA-3505 Turn off ClamAV tcpip mode in tide_core

tide_core.install
relates to https://github.com/dpc-sdp/tide_media/pull/31
skipping the tide_core_update_8015 in CI
=> SDPA-3505 skip the tide_core_update_8015 in CI

css/content_moderation.module.css, css/content_moderation.theme.css, tide_core.libraries.yml, tide_core.module
As a Site Administrator, I would like the log message text field title and help text to change so that it clearly describes what the text field is used for. 
https://digital-engagement.atlassian.net/browse/SDPA-3506
- alter content_moderation_entity_moderation_form form in by implementing a form_alter .
- change $form['revision_log']['#type']=['textfield'] to $form['revision_log']['#type']=['textarea']
- change $form['new_state'] to `Change status to`
- add a  #description form attr to $form['revision_log'] and set the value to be `All content will be published within 24 hours. State below if your content is embargoed or time critical'`
- aligning the forms to be a vertical form by overriding  `content_moderation.module.css`.
https://github.com/dpc-sdp/content-vic-gov-au/pull/749
=> [SDPA-3506] override content_moderation css

dev-tools.sh, tide_core.info.yml
in https://github.com/dpc-sdp/dev-tools/blob/feature/SDPA-3272-update-drupal-8-7/composer.dev.json#L9 branch it requires drupal/core 8.7.6 (commit: https://github.com/dpc-sdp/dev-tools/commit/8571a52b49c0321746cc376b594af602b2cc0b0b), but in tide_core we are using 8.7.9, which is a conflict. 
for fixing this issue, I created a new branch in dev-tools(https://github.com/dpc-sdp/dev-tools/tree/feature/SDPA-3272-update-drupal-to-8-7-9) which is using drupal/core 8.7.9.
=> fixing building failing issue

composer.json, dev-tools.sh
1.  Bumped version of Drupal Core 8.7.11
dpc-sdp/content-vic-gov-au#760
dpc-sdp/tide#86
=> Bump Drupal Core to 8.7.11

composer.json, tide_core.info.yml
https://digital-engagement.atlassian.net/browse/SDPA-4174
1. add drupal/token as a new dependency.
=> [SDPA-4174] lock drupal/token to 1.6

tide_core.module
https://digital-engagement.atlassian.net/browse/SDPA-4203
we cannot achieve the requirement by manipulating permissions as the required logic is only applied to `'node_' . $bundle . '_scheduled_transitions_add_form_form'`, so simply altering the form.
1. scheduled_transitions module change `state` to `transition` key from version1.0 to version 1.1
- more details 
https://git.drupalcode.org/project/scheduled_transitions/-/blob/8.x-1.0/src/Form/Entity/ScheduledTransitionAddForm.php#L175
https://git.drupalcode.org/project/scheduled_transitions/-/blob/8.x-1.1/src/Form/Entity/ScheduledTransitionAddForm.php#L199
so we have to change accordingly 
2. only keep 'publish' and 'archive' options in the `'node_' . $bundle . '_scheduled_transitions_add_form_form'` form. …
=> [SDPA-4203] only keep publish and archive

composer.json, dev-tools.sh
###Jira
https://digital-engagement.atlassian.net/browse/SDPA-4225
1. bumped `drupal/core` to 8.8.6
2. deleted `RSS view with fields give wrong URL from path field`patch
https://github.com/dpc-sdp/dev-tools/pull/36 
https://github.com/dpc-sdp/tide_test/releases/tag/1.2.0
https://github.com/dpc-sdp/content-vic-gov-au/pull/867
=> [SDPA-4225] updates tide_core to be compatible with Drupal 8.8.6

dev-tools.sh
Prior to the release of dpc-sdp/dev-tools 0.4.2 it was necessary to reference the commit that incremented Drupal Core to 8.8.8 so that tests would pass.
=> Reverted dev-tools to master branch.

tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4271
1. the original requirement is to re-order transitions list based on user roles.
1. it could be achieved , but with ugly custom code in form_alter.
2. we might not want to increase its logical complexity 
3. after discussed with Vanessa. we will apply this change to all users.
1. Changes the order of transitions list by change its `weight`.  drupal way 😉
=> [SDPA-4271] Changes the order of transitions list.

tests/behat/features/account.feature, tide_core.install
https://digital-engagement.atlassian.net/browse/SDPSUP-1832
1. Added update hook to change permission to "Visitors, but administrator approval is required" for creating new user.
2. Added hook dependencies.
https://github.com/dpc-sdp/tide_landing_page/pull/95
https://github.com/dpc-sdp/tide_site/pull/57
=> [SDPSUP-1832] Added update hook to change permission for user creation and hook dependencies included.

tide_core.drush.inc
1. the drush function name should be named as `drush_tide_core_scheduled_transitions_queue_jobs`
=> clean up drush 8 command

composer.json, tests/behat/features/access.feature, tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4378
If I enter an invalid username on the login or forgot password pages, the error message indicates if that username is valid.
1. Added username_enumeration_prevention module and update hook to enable it.
2. Added behat test to check the error message doesn't indicate whether the email address is valid or not.
3. Added patch for events_log_track module.
https://github.com/dpc-sdp/content-vic-gov-au/pull/904 ([Test Link](https://nginx-php-content-vic-pr-904.lagoon.vicsdp.amazee.io/))
=> [SDPA-4378] username enumeration prevention

config/install/field.storage.node.field_node_display_headings.yml, tide_core.info.yml, tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-4582
1. Added new field storage for the header radio button (Which will be used to show H2 or H2 and H3 for table of contents.) on and update hook.
https://github.com/dpc-sdp/tide_landing_page/pull/106
https://github.com/dpc-sdp/tide_page/pull/23
https://github.com/dpc-sdp/tide_publication/pull/11
https://github.com/dpc-sdp/content-vic-gov-au/pull/963
=> [SDPA-4582] Added new display headings field storage.

src/Form/NodeActionForm.php
1. the original logic is not that right. 
The correct way:
When we `publish` a node, we are changing the latest revision to `published` state.
=> Fixes publish action bug

modules/tide_oauth/README.md, modules/tide_oauth/drush/tide_oauth.drush.inc, modules/tide_oauth/src/Commands/TideOauthCommands.php, modules/tide_oauth/src/EnvKeyGenerator.php, modules/tide_oauth/tide_oauth.services.yml
```
The post-rollout task runs the Drush command to generate the key pair from the env variables, but it doesn't generate a new key pair if the env variables are not set. We could modify that command to do:
check if there is a valid key pair in private://
if not, try to create a key pair from env variables
if the env variables are not set, generate a new key pair.
```
=> [tide_oauth_changes] Updated drush command to generate keys if no envkeys.

modules/tide_oauth/tide_oauth.install
The **__tide_retrieve_config_uuid_** function wasn't retrieving the UUID for the config at first install, as it couldn't find the config in config/sync. So when it tries to create and save the new field, it couldn't save because it was not entering the UUID check if condition as there wasn't any uuid.
Took out the field id and field save call out of UUID if condition, so the new fields get created and saved at the fiirst install.
=> [client_id_issue] Added fix for tide_oauth client id issue.

tide_core.module
https://digital-engagement.atlassian.net/browse/SDPA-4885
1. grouping `moderation state` into `footer` region.
---
=> [SDPA-4885] Fixes moderation_state layout issue in the clone form

modules/tide_oauth/src/EnvKeyGenerator.php
https://digital-engagement.atlassian.net/browse/SDPSUP-2516
During openshift build, the post-rollout tasks run the drush command to generate the oauth keys [here](https://github.com/dpc-sdp/content-vic-gov-au/blob/develop/.lagoon.yml#L41)
it throws the error saying - 
```
Drupal\simple_oauth\Service\Exception\FilesystemValidationException:     [error]
--
  | Directory "private://" is not a valid directory. in /app/docroot/modules/contrib/simple_oauth/src/Service/Filesystem/FilesystemValidator.php:54
```
The function `generateOauthKeys()` needs to prepare the private directory as well just like how it is done in `generateEnvKeys()`
=> [SDPSUP-2516] Added code to prepare the private directory before generating oauth keys.

modules/tide_oauth/drush.services.yml
```
In YamlPecl.php line 74:
yaml_parse(): parsing error encountered during parsing: did not find expect
ed key (line 5, column 7), context while parsing a block mapping (line 3, c
olumn 5)
```
On upgrade of Drush the above error was thrown for any Drush commands.
Cause was extra indents in the updated file
=> [SDPA-4946] Fixed indentation errors.

composer.json, tide_core.install
https://digital-engagement.atlassian.net/browse/SDPA-5028
Added a new module named tablefield, this is used in tide_landing_page data table PR.
tide_landing_page - https://github.com/dpc-sdp/tide_landing_page/pull/136
Testing link - https://nginx-php.pr-1072.content-vic.sdp1.sdp.vic.gov.au/
=> [SDPA-5028] Added tablefield modules and related permissions.

composer.json
1. Drupalcore releases the latest version recently, unfortunately the XXS patch conflicts with the SA-CORE-2021-002 change in 8.9.14. , so we need to update`Refactor Xss::attributes() to allow filtering of style attribute values - https://www.drupal.org/project/drupal/issues/3109650`.
- https://www.drupal.org/project/drupal/issues/3109650#comment-14068145
2. without updating, a fatal error occurs during `composer update`.
3. sorry about https://github.com/dpc-sdp/tide_core/pull/221, it doesn't correct.
=> Updates xxs patch

tide_core.install
1. the module should get installed from baywatch module
https://github.com/dpc-sdp/baywatch/pull/24
=> Remove the install hook.

tide_core.install
When the `scheduled_transitions` view is yet available during fresh installation, `tide_core_update_8018` creates a malformed View with the following config YML:
```yml
label: 'Scheduled update list'
display:
default:
display_options:
title: 'Scheduled update list'
empty:
area:
content:
value: 'There are no scheduled updates yet.'
format: plain_text
```
This is problematic as it prevents Drupal from importing the correct View upon `drush cim` due to the following error:
```
Error: Call to a member function setSyncing() on null in /app/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php on line 389 #0 /app/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(997): Drupal\Core\Config\Entity\ConfigEntityStorage->importDelete('views.view.sche...', …
```
=> Fixed tide_core_update_8018 and update_8032.

tide_core.module
https://digital-engagement.atlassian.net/browse/SRM-24
Added hook_node_access_records(), hook_node_grants() and hook_node_access() to allow users to view unpublished contents if they have the right permissions.
=> [SRM-24] Added hooks to grant view for unpublished nodes.

modules/tide_paragraphs_enhanced_modal/css/paragraphs.enhanced_modal.css
https://digital-engagement.atlassian.net/browse/SRM-40
When the browser at 601-605 height, some of items in the bottom cannot be reached, and the modal title will be gone.
=> [SRM-40] Fixes `modal items` missing issue

tide_core.install
Fresh install is broken at may places due to incorrect use of `$config_factory->getEditable()` in update hooks.
=> Fixed update hooks with incorrect use of $config_factory->getEditable().

tests/behat/features/account.feature, tide_core.install
Jira: 
https://digital-engagement.atlassian.net/browse/SDPA-4393
[SDPA-4393] Added a hook_update to set the user register to admin_only.
The following updates are pending:
tide_core module :
8050 -   Make user creation admin_only.
Do you wish to run all pending updates? (y/n): y
Finished performing updates.
On-behalf-of: @salsadigitalauorg <joshua.fernandes@salsadigital.com.au>"
[SDPA-4393]: https://digital-engagement.atlassian.net/browse/SDPA-4393
=> Only allowed Admin to register new users.

composer.json, tide_core.info.yml
https://digital-engagement.atlassian.net/browse/SDPA-5632
1.  `event_log_track` module doesn't have Drupal 9 support, so we are going to switch to admin_audit_trail 
1. replace `event_log_track` related code by `admin_audit_trail` one.
2. all `event_log_track` patches are merged to `admin_audit_trail`.
1. This PR is just for disabling event_log_track  and enabling admin_audit_trail.
1. removing event_log_track from composer.json should happen in an another separate hotfix/release.
=> Replaces event_log_track hooks with admin_audit_trail

composer.json
Updated Refactor Xss::attributes() to allow filtering of style attribute values to the latest compatible patch.
On-behalf-of: @salsadigitalauorg joshua.fernandes@salsadigital.com.au
=> Updated Refactor Xss::attributes() to allow filtering of style attribute values to the latest compatible patch.

tide_core.module
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-5664
Changes:
1) When the CMS user edits a menu item and saves it, the user is redirected to the menu collections page.
2) The function "tide_core_menu_submit_handler" is added for the redirect as the "$form_state->setRedirectUrl(<URL>) function if added in the "tide_core_form_alter" function in tide_core.module does not set the redirect.
Test PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/1264
=> [SDPA-5664] Redirect "Edit menu" page to menu collection on save

modules/tide_edit_protection/tide_edit_protection.module
Fix error:
```
Error: Call to a member function __toString() on string in tide_edit_protection_preprocess_status_messages() (line 167 of /app/docroot/modules/contrib/tide_core/modules/tide_edit_protection/tide_edit_protection.module)
#0 /app/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(287): tide_edit_protection_preprocess_status_messages(Array, 'status_messages', Array)
#1 /app/docroot/core/lib/Drupal/Core/Render/Renderer.php(436): Drupal\Core\Theme\ThemeManager->render('status_messages', Array)
```
=> Fixed fatal error from tide_edit_protection_preprocess_status_messages.

tide_core.module
**JIRA** - https://digital-engagement.atlassian.net/browse/SDPA-5969
Changes
1) Make the email field required for all user types when creating a new user.
=> [SDPA-5969] Make CMS user email required during user creation

src/TideCommonServices.php, tests/src/Unit/TideCommonServicesTest.php, tide_core.services.yml
https://digital-engagement.atlassian.net/browse/SW-1640
In the content-premier site `3.0.7-p2`, `tide_media` is 3.0.4 which has a feature: https://github.com/dpc-sdp/tide_media/pull/82 that depends on https://github.com/dpc-sdp/tide_core/blob/develop/tide_core.services.yml#L17 service, but `tide_core.common_services` was not included into the release.
We don't want to include other changes from develop branch, so we cherry-pick the specific change https://github.com/dpc-sdp/tide_core/commit/d298a593dcb700a00f3c268a3a8079ad5b8baba9.
relates to 
- https://github.com/dpc-sdp/content-premier-vic-gov-au/pull/165
- https://github.com/dpc-sdp/tide_media/pull/82
=> cherry-pick: [SDPA-5443] Tide Core Common Services Helper

modules/tide_cms_support/tide_cms_support.install
Ticket: https://digital-engagement.atlassian.net/browse/SDPA-5959
- Remove install CMS Help block from `tide_cms_support`
During fresh install of `tide_core` and `tide_cms_support` the Admin theme is not available, so installation of the CMS Help block fails. 
See error during builds -
Moving this block placement into the Tide Profile install process where the Admin theme will be available.
=> [SDPA-5959] Move CMS help block install to tide profile

composer.json
Removed an outdated patch
https://www.drupal.org/project/jquery_ui_touch_punch/issues/3159222
The issue has been fixed from the upstream.
=> Removed an outdated patch

composer.json
**Jira:**  https://digital-engagement.atlassian.net/browse/SRM-436
Changes:
1. Use rerolled patch as metadata module is upgraded to [8.x-1.20](https://www.drupal.org/project/metatag/releases/8.x-1.20)
**Links**
https://www.drupal.org/project/metatag/issues/2945817
=> [SRM-436] Re roll Metadata module patch for Issue:2945817

includes/helpers.inc
This function breaks the UUID sometimes, it should be removed before tide_core 4.x
=> Deprecated _tide_import_single_config method

config/install/user.role.editor.yml, tests/behat/features/workflow.feature, tide_core.install
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPAP-5665
1. Based on defect found [https://digital-vic.atlassian.net/browse/SDPAP-5665?focusedCommentId=141936], update the permissions for editor role to remove access for content moderation section.
**Administrator**
**Approver**
**Editor**
=> [SDPAP-5665] Add moderated content submenu to Content Menu

tide_core.info.yml
Jira - https://digital-vic.atlassian.net/browse/DDS-1348
This PR enables two additional admin_audit_trail submodules which will audit when changes are made to redirects and blocks.
=> [DDS-1349] Enable more admin_audit_trail submodules.

src/Render/Element/AdminToolbar.php, tide_core.module
Jirra: https://digital-vic.atlassian.net/browse/SDPAP-5303
**Navigating long menus in the CMS**
As a CMS user I want to easily navigate through long drop-down menus in the CMS admin console to find the item I am looking for.
Background
As the CMS is growing the menu drop-downs are becoming bigger and bigger. There is currently no way of navigating through long navigation lists as items get cut off at the bottom of the screen. 
This is only an issue on two menu items:
Structure > Menus
Structure > Taxonomy
After a UX review [https://digital-vic.atlassian.net/browse/SDPA-5543 - Can't find link](https://digital-vic.atlassian.net/browse/SDPA-5543) the current solution is to:
remove the long secondary dropdowns (level 3) as they are not scalable, and
make users access the child options by …
=> SDPAP-5303: Navigating long menus in the CMS.

tide_core.module
https://digital-vic.atlassian.net/browse/SDPAP-7127
There are 2 error messages in the local and develop(could be found in the dblog)  environments, which may relate to [https://digital-vic.atlassian.net/browse/SDPAP-5303](https://digital-vic.atlassian.net/browse/SDPAP-5303) 
https://develop.content.vic.gov.au/admin/reports/dblog/event/3
1. Added additional conditions in tide_core_menu_navigation_links under tide_core.module file and revised the way of unsetting subtree menu for Taxonomy and Menu Navigation by emptying $element->subtree instead of unsetting it which will totally removed the array variable from the menu tree.
=> SDPAP-7127 Fixed undefined property captured for menus

src/Plugin/Field/FieldWidget/PresetParagraphsWidget.php
https://digital-vic.atlassian.net/browse/SRM-664
The media: buying for vic content type uses a link paragraph type which has a widget type set to PresetParagraphsWidget. tide_core has a custom plugin for this and [this place](https://github.com/dpc-sdp/tide_core/blob/develop/src/Plugin/Field/FieldWidget/PresetParagraphsWidget.php#L104) gets the preset_number from field config [here](https://github.com/dpc-sdp/content-vic-gov-au/blob/develop/config/sync/core.entity_form_display.node.media_buying_for_vic.default.yml#L338) and before it used to return a numeric value instead of empty string. With all the changes, its now returns exactly an empty string and which triggers the above error [in this line](https://github.com/dpc-sdp/tide_core/blob/develop/src/Plugin/Field/FieldWidget/PresetParagra …
=> Updated plugin implementation of entity_reference paragraphs widget.

config/install/field.field.paragraph.related_links.field_paragraph_link.yml, tide_core.install, tide_core.module
https://digital-vic.atlassian.net/browse/SDPAP-7077
In this component, the URL field is mandatory. But the Link text field is currently not mandatory. The Link text field needs to be mandatory in order for the link to display.
If a CMS user fills the URL field but not the Link text field, they are able to save the node/page OK but on the front end, if there is no content in the Link text field, no link will display.
1. Made 'Related link' mandatory and added help text.
BE: https://github.com/dpc-sdp/content-reference-sdp-vic-gov-au/pull/202 | https://nginx-php.pr-202.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
Before:
After:
=> [SDPAP-7077] Related link mandatory and help text.

composer.json, config/optional/views.view.files.yml, tide_core.install
https://digital-vic.atlassian.net/browse/SDPAP-7132
There is a bug in an “Automated config export” script that added a Views config file containing a single line “status: false”. This config was imported by Drupal and resulted in an uncaught exception - White Screen of Death - error for every page load on the CMS.
When trying to change the "status", the config file could not be found, resulting in creation of an empty config file and inserted a single line "status: false".
Added views.view.files to config/optional so during install, it will find the config. Config file has set "status: false".
=> [SDPAP-7132] Automated config export cause drupal WSOD error.

modules/tide_site_alert/css/site_alert.css, modules/tide_site_alert/tide_site_alert.module
https://digital-vic.atlassian.net/browse/SDPAP-7334
The support team would like to use of the severity fields in the alert module. 
Red banner at the top of the screen below the drupal menu (Severity = High)
Yellow banner at the top of the screen below the drupal menu (Severity = Medium)
Blue banner at the top of the screen below the drupal menu (Severity = Low)
https://nginx-php.pr-218.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
=> [SDPAP-7334] Alert for CMS users - Severity levels

tide_core.install
https://digital-vic.atlassian.net/browse/SDPAP-7108
1. It causes issues for tide_site as tide_site not dependant on tide_landing_page  and creates a garbage field as the field is not provided by tide_core. This hook should have been added in tide_landing_page
2. It causes issues for tide_landing_page as well, cause tide_landing_page already has this field in the active config and then tide_core tries to add it again while running this hook and creates conflicts
1. Commenting out the hook so that it does not run this on other modules where tide_core is added as a dependency.
=> Commented updated hook.

composer.json
Fixes an issue where DateTimeComputed tries to compute from an empty value
https://digital-vic.atlassian.net/browse/SDPAP-7631
URL: https://nginx-php.pr-206.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/node/add/event
Issue: After expanding the Feature Image toggle, and then clicking the ‘Select images' button, the modal for image selection is not displayed - the user is redirected to the Body Content tab
Expected: modal window to select image is displayed
https://www.drupal.org/project/drupal/issues/3052608
we may apply/reroll more patches till it is finally fixed.
=> [SDPAP-7631] DateTimeComputed tries to compute from an empty value

tide_core.links.task.yml
https://digital-vic.atlassian.net/browse/SDPAP-7401
Currently content Navigation Bar has two options for Scheduling Updates not only content-vic but content-reference, content-vicpol,etc. Both schedule transition and schedule update are linking to schedule transition. 
We want to remove 'Schedule update' and keep 'Schedule transition' instead
BE LINK: https://nginx-php.pr-233.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/admin/content
By deleting tide_core.links.task.yml
=> [SDPAP-7401]delete link task for schedules update

composer.json
Using a noncanonical repository (fork) that originates from a Drupal ticket for issue resolution can potentially lead to a broken composer. This may happen if the changes are merged into the main branch and the forked repository is subsequently closed and deleted.
=> Remove noncanonical repository(entity_embed)

composer.json
=> Bump metatag to 2.x

composer.json
https://www.drupal.org/project/editor_advanced_link/issues/3370300
Locking the editor_advanced_link module to last working version with ck5.
=> Locked editor_advanced_link module to a working version with ck5.

composer.json
no jira ticket
'Unsafe-eval' required after update to 2.2.1
https://www.drupal.org/project/editor_advanced_link/issues/3370300
=> fix: editor_advanced_link errors

composer.json
https://digital-vic.atlassian.net/browse/DDS-1474
https://www.drupal.org/project/drupal/issues/3207813
Due to the way the Shield module behaves when used in combination with the Key module, corruption of the bootstrap system can occur as Shield attempts to use entityTypeManager too early in the request lifecycle before module files are loaded. This can cause the module_implements cache to be populated with missing data and as a result, hooks such as hook_entity_type_alter are no longer effective.
Patch ModuleHandler to load all module files if invoked from an http_middleware service while the `module_implements` cache is not yet populated.
=> [DDS-1474] Fix bootstrap system corruption under high traffic

tide_core.info.yml, tide_core.install
https://digital-vic.atlassian.net/browse/SDPAP-8093
Some of the module was deprecated in Drupal 9.4 and the code package reference is removed from Drupal 10. So those modules needs to be uninstalled first from SDP projects before installing the Drupal 10
1. Removed Deprecated modules in 9.4 and added update hook to clean it from all existing projects.
2.
=> [SDPAP-8093] remove deprecated modules before d10 update

tide_core.module
https://digital-vic.atlassian.net/browse/SDPAP-8299
Null check for moderation state to avoid this kind behaviour for content types that does not have any moderation state.
=> [SDPAP-8299] Added null check for moderation state.

composer.json
https://digital-vic.atlassian.net/browse/SDPAP-8087
The site_alert js is making a POST request to the {{ajax/site_alert}}resource every 5 seconds.
This leads to a significant number of requests being made to the CMS that cannot be cached.
Use HTTP GET to allow caching of AJAX request
https://www.drupal.org/project/site_alert/issues/3160200#comment-15217710
The router responsible for handling `ajax/site_alert` requests has already cached the response.
https://git.drupalcode.org/issue/site_alert-3160200/-/blob/3160200-use-http-get/src/Controller/SiteAlertController.php#L126
=> [SDPAP-8087] Use GET to allow AJAX request

config/optional/pathauto.settings.yml, tide_core.install
https://digital-vic.atlassian.net/browse/SDPAP-8260
1. Change the max_length of pathauto.settings.yml to 255 characters
2. Add an update hook to implement the change.
=> [SDPAP-8260] Increase character limit of URLs

includes/helpers.inc
We don't use D8 anymore, so there's a large block of code here not required for our purposes.
I noticed this while checking to see if there is a helper method to assist in config checking prior to import.
=> Fix version checking block on helper method

composer.json
A build over in tide_search (https://github.com/dpc-sdp/tide_search/pull/58) has discovered an issue with the patch here, so it should be removed since it's now in release.
=> Update requirements to remove broken patch

config/install/user.role.approver.yml, src/Form/NodeActionForm.php, tests/behat/features/bulk_update.feature, tide_core.install, tide_core.permissions.yml
https://digital-vic.atlassian.net/browse/SDPAP-7103
The update includes the implementation of the `tide node bulk update` permission and the necessary code changes.
- https://github.com/dpc-sdp/dev-tools/pull/104
=> [SDPAP-7103] Enable bulk publishing for Approvers

css/claro_layout.css, tide_core.libraries.yml
https://digital-vic.atlassian.net/browse/SRM-1187
There are some new css changes in the BE in D10 and which changes our default design for node add/edit form.
Added custom css to retain the fullwidth design for node add/edit form
The current screenshot after fix - 
See the screenshots of the issue in the ticket
=> Added custom css to adjust the width of node form to match SDP current design.

composer.json
https://digital-vic.atlassian.net/browse/SRM-1174
it works fine with D10
```cli
[content-vic]cli-drupal:/app$ drush cron
[warning] Processing per role expiration warning.
[notice] Starting data export..
>  [notice] operation:insert, description:private://views_data_export/vsba_data_extract_data_export_1/1-1701311478/vsba_data_extract.csv, ref_numeric:620168, ref_char:vsba_data_extract.csv, uid:1, path:
>  [notice] operation:update, description:private://views_data_export/vsba_data_extract_data_export_1/1-1701311478/vsba_data_extract.csv, ref_numeric:620168, ref_char:vsba_data_extract.csv, uid:1, path:
>  [notice] Data export saved to private://views_data_export/extract.csv
[success] Data export finished.
```
=> [SRM-1174] update views_data_export’s patch

composer.json
The following warning pops up when pushing a pr in tide_api and it is because of 
deprecated function: Creation of dynamic property Drupal\content_lock\ContentLock\ContentLock::$time is deprecated in Drupal\content_lock\ContentLock\ContentLock->__construct() (line 139 of modules/contrib/content_lock/src/ContentLock/ContentLock.php).
https://www.drupal.org/project/content_lock/issues/3343964
=> adding patch for content lock

composer.json
dev-master has an update for symfony/polyfill-mbstring which creates conflicts with drupal core 10.1.x dependency.
Lock it to a stable latest release tag to avoid this conflicts.
=> Locked respect/validation to latest release to avoid composer conflicts.

composer.json
Recent release has bug fixes and also some projects using config_filter 2.0 and that is why the newer version becomes a dependency.
Upgraded config_split with newer release.
=> Updated config_split version with the recent release.

modules/tide_cms_support/tide_cms_support.links.menu.yml, tests/behat/features/cms_support.feature
https://digital-vic.atlassian.net/browse/SDPAP-8367
> Please remove the remove dropdown items from the ‘CMS Support’ tab in the CMS. Instead could we please change the text ‘CMS support’ to ‘Help’ and link straight to [SDP Help Centre](https://digital-vic.atlassian.net/servicedesk/customer/portal/14/article/2030338745?src=1792308362).
=> [SDPAP-8367] Changes CMS support dropdown

composer.json, config/install/field.storage.node.field_content_category.yml, config/install/taxonomy.vocabulary.content_category.yml, css/pseudo_required_field.css, includes/helpers.inc, includes/updates.inc, src/TideCoreOperation.php, tide_core.info.yml, tide_core.install, tide_core.libraries.yml, tide_core.module
https://digital-vic.atlassian.net/browse/SDPAP-8421
- https://github.com/dpc-sdp/tide_event/pull/71
- https://github.com/dpc-sdp/tide_grant/pull/31
- https://github.com/dpc-sdp/tide_news/pull/44
- https://github.com/dpc-sdp/tide_search/pull/59
- https://github.com/dpc-sdp/tide_landing_page/pull/216
- https://github.com/dpc-sdp/tide_publication/pull/37
=> [SDPAP-8421]Adds content category terms.

tide_core.install
During content-vic release 1.48 a hook update was failing in getting the id name. 
Added a workaround to get the id name.
=> updated hook update

composer.json
https://www.drupal.org/project/user_expire/issues/3253423
It has been fixed upstream, so we have removed it.
=> Removed the patch for user_expire as it has fixed

composer.json
https://digital-vic.atlassian.net/browse/SD-183
The release of the new version(before yesterday) of the `embed` https://www.drupal.org/project/embed  module has resolved our issue, as mentioned here: https://www.drupal.org/project/entity_embed/issues/3466609#comment-15723516. The suggested patch is no longer necessary (and it could break webform creation again @pmethukupally indentified. )
=> Remove the unnecessary patch for entity_embed

composer.json, config/install/monitoring.sensor_config.tide_times.yml, src/Controller/SystemInfoController.php, src/Plugin/monitoring/SensorPlugin/TidetimesSensorPlugin.php, src/TideSystemInfoService.php, tests/src/Kernel/SystemInfoControllerTest.php, tide_core.info.yml, tide_core.install, tide_core.routing.yml, tide_core.services.yml
https://digital-vic.atlassian.net/browse/SD-188
> As a tester,
I want to be able to get the Tide package version and SDP version via an API,
So that I know what versions have been deployed on different environments for release management and visibility
~Apart from `/api/v1/system-info`, `/api/v1/system-info/fields/{types}` has also been introduced to better explain the back-end compatibility.~
/pkg-version
```json
{
"package_versions": {
"drupal/core": "10.3.5",
"dpc-sdp/tide": "dev-mono-repo-test",
"dpc-sdp/tide_core": "dev-feature/SD-268-mono-repo-phase-1",
"drush/drush": "12.5.3",
"php": "8.3.10"
}
}
```
/fields-info
/fields-info/node
/fields-info/node,media
```
{
"media": {
"audio": [
"field_license_type",
"field_media_audience",
"field_media_department",
"field_media_file", …
```
=> [SD-188] tide version information

modules/tide_landing_page/tide_landing_page.module, tide_core.install
There is currently a conflict between the TFA password reset and the [PRLP](https://www.drupal.org/project/prlp) module. We need an SDP-specific patch to ensure the PRLP password reset functions correctly with TFA. Without this patch, the TFA module bypasses the PRLP service and instead calls Drupal core's default password reset service.
1. We will stop auto-enabling the tide_tfa module for all projects. Although the TFA code works as expected, we will only enable it on a project-by-project basis after implementing the SDP-specific patch that resolves the password reset issue. This will ensure proper integration between TFA and PRLP.
2. Removed duplicate sate js addition in landing page module as that addition is moved to tide_core.module.
=> Added code clean up and remove tfa enable with hook.

modules/tide_site/src/Plugin/Linkit/Substitution/Canonical.php
`PHP Fatal error:  Declaration of Drupal\tide_site\Plugin\Linkit\Substitution\Canonical::getUrl(Drupal\Core\Entity\EntityInterface $entity) must be compatible with Drupal\linkit\Plugin\Linkit\Substitution\Canonical::getUrl(Drupal\Core\Entity\EntityInterface $entity, array $options = []) in /app/docroot/modules/contrib/tide_core/modules/tide_site/src/Plugin/Linkit/Substitution/Canonical.php on line 70`
Updated the overriding function.
It is related to the latest linkit module release and this patch to be specific which updates the getUrl function - https://www.drupal.org/project/linkit/issues/3022261
=> Updated function to be compatible with the base one.

modules/tide_site/src/AliasManager.php
Content-vic and other projects are having behat test failied because of optional parameter $time declared before required parameter $alias_helper.
Make time parameter required, as this needs to be required anyway from D11 and also deprecated in 10.3 version of Drupal. Based on this - https://www.drupal.org/node/3387233
So we can remove the optional part for time in the overriding function and keep the constructor parameter sequence same.
https://github.com/dpc-sdp/content-vic-gov-au/pull/1725
=> reorder parameters

modules/tide_publication/config/install/core.entity_view_display.node.publication_page.default.yml, modules/tide_publication/config/install/field.field.node.publication_page.field_content_category.yml, modules/tide_publication/tests/behat/features/fields.feature, modules/tide_publication/tide_publication.install
https://digital-vic.atlassian.net/browse/SD-356
Testing link: https://nginx-php.pr-454.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
Content category section not available on publication page content type
Added content category field to publication page.
=> [SD-356]added content category to publication page

modules/tide_site/tide_site.install, tide_core.install
1. After moving to mono repo, the cofig location change and causing issues for the sites that are behind few releases.
2. The sites that are behind few releases, the update hook creates dependencies cause the module enabled in one release and fields updated in the next one
1. Updated config location
2. Updated hook dependencies.
=> Added hook dependency and updated config location.

modules/tide_api/src/Plugin/jsonapi/FieldEnhancer/YamlEnhancer.php
Logs are full of errors such as these
```
Warning: Trying to access array offset on null in Drupal\\tide_api\\Plugin\\jsonapi\\FieldEnhancer\\YamlEnhancer->doUndoTransform() (line 27 of /app/docroot/modules/contrib/tide_core/modules/tide_api/src/Plugin/jsonapi/FieldEnhancer/YamlEnhancer.php) #0 /app/docroot/core/includes/bootstrap.inc(166): _drupal_error_handler_real()
#1 /app/docroot/modules/contrib/tide_core/modules/tide_api/src/Plugin/jsonapi/FieldEnhancer/YamlEnhancer.php(27): _drupal_error_handler()
#2 /app/vendor/e0ipso/shaper/src/DataAdaptor/DataAdaptorTransformerTrait.php(57): Drupal\\tide_api\\Plugin\\jsonapi\\FieldEnhancer\\YamlEnhancer->doUndoTransform()
#3 /app/docroot/modules/contrib/jsonapi_extras/src/Normalizer/ResourceObjectNormalizer.php(56): …
```
=> Fixed PHP warning for accessing array offset on null

modules/tide_landing_page/config/install/field.field.paragraph.key_journeys.field_paragraph_title.yml, modules/tide_landing_page/tide_landing_page.install, modules/tide_landing_page/tide_landing_page.module
https://digital-vic.atlassian.net/browse/SD-416
This PR fixes an issue with incorrect settings where the `#placeholder` and `#default_value` conflict.
=> [SD-416] Fixes placeholder issue for `Header links`

modules/tide_publication/src/Controller/PublicationResource.php
https://digital-vic.atlassian.net/browse/SD-360
cache `::buildHierarchy` results. since `::buildHierarchy` consumes a significant amount of resources, it's surprising that the results are not being cached~
=> [SD-360] Refactor ::getHierarchy

composer.json
During the release, discovered that the "Add pagination to target revision candidates list" patch for `scheduled_transitions` is no longer compatible. Considering the size of the patch, re-rolling is not attempted for now, so, temporarily lock `scheduled_transitions` module version to `2.5` to proceed with the release.
follow up https://digital-vic.atlassian.net/browse/SD-534
=> lock scheduled_transitions to 2.5

modules/tide_landing_page/src/Plugin/jsonapi/FieldEnhancer/BasicTextEnhancer.php
https://digital-vic.atlassian.net/browse/SD-535
The character`Â` and other odd characters typically appear due to an encoding mismatch.
Update `BasicTextEnhancer.php` to deal with this issue by explicitly specify the DOM will be UTF-8.
=> [SD-535] Fixes character encoding strangeness

css/ckeditor_overrides.css
https://digital-vic.atlassian.net/browse/SD-393
Link search popup in ckeditor is having transparent background on searching link.
1. Added background color in ckeditor override css.
=> Fixed link search background issue in ckeditor ribbon

modules/tide_paragraphs_enhanced_modal/css/paragraphs.enhanced_modal.css
https://digital-vic.atlassian.net/browse/SD-551
BE link: https://nginx-php.pr-1756.content-vic.sdp4.sdp.vic.gov.au/
Heading for AV is not fully visible:
Fixed styling by adding text-wrap property.
=> [SD-551]AV-heading-not-visible

modules/tide_media/tide_media.module
https://digital-vic.atlassian.net/browse/SD-460
Testing link in content-vic: https://nginx-php.pr-1755.content-vic.sdp4.sdp.vic.gov.au/
Hide edit tab user by adding a menu local task alter function in vicgovau_core.module and unset the tab for a Secure File User role.
2.Redirect the link content.vic/user/user_id/edit to content.vic/user/user_id/ in a preprocess_page function.
Note: I discovered that the "Secure File" user role is missing the necessary permissions. For testing purposes, I manually enabled the toolbar to allow the user to log out. I will be creating a new ticket with all relevant details for further investigation and resolution.
=> added menu local task alter to restrict edit profile for securefile user

composer.json, config/install/media_alias_display.settings.yml, modules/tide_media/tide_media.install, tide_core.module
https://digital-vic.atlassian.net/browse/SD-518
Media library - allow alias for media items
Integrated new media file alias module with only document file type enabled. Also this module depends on media library from core which seems not enabled globally. Please advise if we can enable it too.
=> Settings for media alias display for documents type

modules/tide_ckeditor/src/Plugin/EmbeddedContent/TideIframe.php
https://digital-vic.atlassian.net/browse/SD-623
The height and width fields are mandatory in the iframe embed modal and it needs to be changed to non mandatory.
Removed '#required' => TRUE, for both width and height
=> [SD-623]remove required height and width for embedded content

modules/tide_landing_page/config/install/core.entity_form_display.paragraph.key_journeys.default.yml, modules/tide_landing_page/tide_landing_page.install
https://digital-vic.atlassian.net/browse/SD-709
Testing link: https://nginx-php.pr-502.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
Landing Page Header Links URL display change
The cause of this issue was one config file that has been updated to linkit. Only the view form was needed it so I am reverting the form file and removing it from the hook update.
=> [SD-709]revert linkit in paragraph key journeys

modules/tide_api/src/Plugin/jsonapi/FieldEnhancer/YamlEnhancer.php, modules/tide_search/src/Commands/TideSearchCommands.php
https://digital-vic.atlassian.net/browse/SDPSUP-8990
D10 requires that all entity queries have an explicit access check. See https://www.drupal.org/node/3201242 for reference.
> For Drupal 10 this will be enforced by throwing an exception if ::accessCheck() is not called.
While there, the help text has been corrected and had some examples added because I forget how to use it every time :)
Add the access check.
=> Update audit node command for D10

modules/tide_webform/src/Plugin/WebformElement/WebformReviewComponent.php
https://digital-vic.atlassian.net/browse/SD-578
Testing link: https://nginx-php.pr-1805.content-vic.sdp4.sdp.vic.gov.au/
The frontend needed a new placeholder field to allow for a review component to be inserted in the correct location.
Adds a new webform field that acts placeholder, meaning it doesn't need all the extra field options that other fields have.
Hey @anthony-malkoun @yeniatencio, does this need a test? I could look at adding a test for a multistep/wizard form that includes this. Also, I don't have any contextual knowledge here so please let me know if I've missed anything and or done anything incorrectly. Thanks
=> [SD-578] add review component field

config/install/user.role.approver.yml, modules/tide_media/tide_media.install
https://digital-vic.atlassian.net/browse/SD-675
Testing link: https://nginx-php.pr-511.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
Approver role should be able to delete any media
Add a update hook to assign the permission to approver in tide_media module
=> [SD-675]added edit any media permission to approver

modules/tide_webform/src/Commands/TideWebformSubmissionsCleanUp.php
https://digital-vic.atlassian.net/browse/SD-642
```
drush tide_webform:cleanup_submissions [webform_id] [date_parameter] [end_date]
drush tsc [webform_id] [date_parameter] [end_date]
```
1. Delete submissions from a specific date
`drush tsc tide_webform_content_rating 07-May-2024`
2. Delete submissions within a date range
`drush tsc tide_webform_content_rating 07-May-2024 01-May-2024`
3. Delete submissions older than X days
`drush tsc tide_webform_content_rating 30`
This will delete all submissions older than 30 days.
```
DD-MMM-YYYY (e.g., 07-May-2024)
D-MMM-YYYY (e.g., 7-May-2024)
DD-MONTH-YYYY (e.g., 07-May-2024)
D-MONTH-YYYY (e.g., 7-May-2024)
YYYY-MM-DD (e.g., 2024-05-07)
```
1. The command processes submissions in batches of 100
2. This command will be applied to [this …
=> [SD-642] Improve cleaning of expired submissions

modules/tide_publication/tide_publication.install, src/TideEntityUpdateHelper.php
https://digital-vic.atlassian.net/browse/SD-880
This PR mainly fixes a positioning issue for content-vic (and possibly other sites). I also saw it as a good opportunity to update some helper functions.
We are introducing a new `revert` function, which is essentially like running `drush cim`, but it updates the active configuration with the inactive configurations. The `import` function is also based on `drush cim`, but it’s used to import 
new configurations.
We are also updating the `repositionEntityFormDisplayFields` function by adding a new parameter that lets you specify whether you want to position the field _before_ or _after_ another field visually.
=> [SD-800] Fixes position for the field_topic field.

composer.json
https://digital-vic.atlassian.net/browse/SD-903
- https://www.drupal.org/sa-contrib-2025-023
- https://git.drupalcode.org/project/tfa/-/compare/8.x-1.9...8.x-1.10?from_project_id=57554
To address compatibility issues introduced by drupal/tfa 1.10, this change pins the drupal/tfa dependency to version 1.9 in our composer.json. 
Upgrades to 1.10 will be rolled out as part of a future tide release.
=> [SD-903] Pin TFA to 1.9 for compatibility

composer.json, modules/tide_event/config/install/core.entity_form_display.node.event.default.yml, modules/tide_event/config/install/core.entity_view_display.node.event.default.yml, modules/tide_event/config/install/field.field.node.event.field_bottom_graphical_image.yml, modules/tide_event/config/install/field.field.node.event.field_graphical_image.yml, modules/tide_event/tests/behat/features/fields.feature, modules/tide_event/tests/behat/features/webform.feature, modules/tide_event/tide_event.install, modules/tide_event/tide_event.module, modules/tide_grant/config/install/core.entity_form_display.node.grant.default.yml, modules/tide_grant/config/install/core.entity_view_display.node.grant.default.yml, modules/tide_grant/config/install/field.field.node.grant.field_bottom_graphical_image.yml, modules/tide_grant/config/install/field.field.node.grant.field_graphical_image.yml, modules/tide_grant/tests/behat/features/fields.feature, modules/tide_grant/tide_grant.install, modules/tide_grant/tide_grant.module, modules/tide_news/config/install/core.entity_form_display.node.news.default.yml, modules/tide_news/config/install/core.entity_view_display.node.news.default.yml, modules/tide_news/config/install/field.field.node.news.field_bottom_graphical_image.yml, modules/tide_news/config/install/field.field.node.news.field_graphical_image.yml, modules/tide_news/tests/behat/features/fields.feature, modules/tide_news/tide_news.install, modules/tide_news/tide_news.module, modules/tide_publication/tests/behat/features/fields.feature, src/TideCoreFormHelper.php
https://digital-vic.atlassian.net/browse/SD-745
https://digital-vic.atlassian.net/browse/SD-744
https://digital-vic.atlassian.net/browse/SD-743
Testing link: https://nginx-php.pr-550.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
allow users to add a top and / or bottom corner graphic to the news item content type
if top and / or bottom corner graphic images are added, this will over ride any site or site section images
if no top and / or bottom corner graphic, then it is expected that the site section or site top and / or bottom corner graphics will be used 
Create a helper functions for altering node forms.
Added top and bottom corner graphics in news, event, grant.
Updated behat tests
Added hook update .
Adding patch for admin_toolbar module as 2 days ago there was a new release …
=> [SD-745]added helper to add corner graphics

composer.json
Yesterday a new release for JSON:API Menu Items has been launched and this [patch](https://www.drupal.org/project/jsonapi_menu_items/issues/3350524#comment-15577964) is not needed anymore.
=> remove patch jsoapi menu items

composer.json, tide_core.module
https://digital-vic.atlassian.net/browse/SD-995
During the cloning process, certain fields may not be present on all content types. Attempting to set a value—such as NULL—on a field that doesn't exist causes a fatal error.
1. Added a a simple check if node has the field and then set it as null.
=> [SD-995] Added field check before trying to set the field as null.

composer.json, modules/tide_jira/src/Plugin/monitoring/SensorPlugin/TideJiraSensorPlugin.php, modules/tide_ui_restriction/tide_ui_restriction.module, src/Plugin/monitoring/SensorPlugin/TideSmtpSensorPlugin.php, src/Plugin/monitoring/SensorPlugin/TidetimesSensorPlugin.php, tests/behat/features/text_formats.feature, tests/behat/features/workflow.feature
This PR addresses issues introduced during the initial Drupal 10.4.x upgrade,to ensure consistency between the business logic and the tests.
It includes,
1. Reverted the tests to their previous state.
2. Removed the patch for `drupal/monitoring`
3. Add required annotation for `@SensorPlugin`
4. removed `'/admin/config/people/tfa',` from `tide_ui_restriction_admin_config_access_check_exclude`
=> Revert and fix changes related to Drupal 10.4.x upgrade

modules/tide_landing_page/tide_landing_page.install, modules/tide_publication/tide_publication.install, modules/tide_search/tide_search.info.yml, modules/tide_search/tide_search.install, modules/tide_site/tide_site.module, tide_core.info.yml, tide_core.install
https://digital-vic.atlassian.net/browse/SD-1027
This PR addresses the issues identified during the release.
1.  Move search_api to the tide_core level to fix dependency issues when submodules use it in their logic.
2. Add logics to `hook_update_dependencies` to ensure the update hooks run in a currect order.
3. Update tide_site_entity_presave to handle the user entity form case.
=> [Release 1.54.0 issues] [SD-1027] Fix relation issue from search_api_exclude_entity

composer.json
https://digital-vic.atlassian.net/browse/SDPPE-1
Without this patch, we're encountering issues where search API gets 403 errors, because the index prefixes are being mangled by stripping out dash characters (which are present in most lagoon project names).
Without the patch, index operations are going to this
```
POST; /contentvic__pr1875__sapi_media/_bulk`
```
which does not match the index prefix for the RBAC system. So it gets a HTTP 403 response.
Once the dashes are preserved in the elasticsearch_connector config, it hits
```
POST; /content-vic__pr-1875__sapi_media/_bulk
```
Which is OK!
Adds patch to include `-` characters in elasticsearch_connector index names.
- https://github.com/dpc-sdp/sdp-cmdb/pull/1709
- https://github.com/dpc-sdp/ansible-role-sdp-tide-platform/pull/183
- …
=> [SDPPE-1] Added patch to allow dashes in index names using elasticsearch_connector
